# Generated by Django 4.2.6 on 2023-11-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=25, unique=True)),
                ('direction', models.TextField(default='')),
                ('id_list_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_products.list_product')),
            ],
            options={
                'db_table': 'shopping_carts',
            },
        ),
    ]
