# Generated by Django 4.2.6 on 2023-11-13 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsShopCart', '0001_initial'),
        ('shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='id_list_product',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='items',
            field=models.ManyToManyField(to='itemsShopCart.itemshopcart'),
        ),
    ]
