# Generated by Django 4.2.6 on 2023-11-15 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
        ('shopping_carts', '0003_shopping_cart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_method.paymentmethod'),
        ),
    ]
