# Generated by Django 4.2.6 on 2023-11-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsShopCart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemshopcart',
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='itemshopcart',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
