# Generated by Django 4.2.6 on 2023-11-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=18)),
                ('direction', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
                ('id_shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_carts.shopping_cart')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
