# Generated by Django 4.2.6 on 2023-11-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_shopping_cart',
        ),
    ]
