# Generated by Django 4.2.6 on 2023-11-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PaymenMethod',
            },
        ),
    ]
