# Generated by Django 4.2.6 on 2023-11-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('customs_code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('number_order', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
